### ISSUE TITLE
serversession-backend-persistent-1.0 can't compile its test suite

### ISSUE THREAD

**Issue by peti** [yesodweb/serversession#2]
Citing from http://hydra.cryp.to/build/933780/log/raw:

```
Preprocessing test suite 'tests' for serversession-backend-persistent-1.0...
ghc: unrecognised flag: -s
did you mean one of:
  -n
  -F
  -v
unrecognised flag: -M1G

Usage: For basic information, try the `--help' option.
```

**Comment by meteficha** [comment]
Thanks for the report, @peti!  This is a funny issue.  How exactly is `cabal-install` being called by your build system?  Here's the relevant line from the cabal file:

```
  ghc-options:     -Wall -threaded "-with-rtsopts=-N -s -M1G -c" -rtsopts
```

It seems your build is ignoring the quotes around the RTS options.  I have no idea what could cause this.

**Comment by peti** [comment]
We do the normal "ghc --make Setup && ./Setup configure && ./Setup build && ..." thing. We don't use `cabal-install` at all.

**Comment by meteficha** [comment]
I'm afraid I don't know how to reproduce this problem on my machine :(.

**Comment by peti** [comment]
You are right, this appears to be a problem in our build process. Give me a moment, I'll have to run some tests ....

**Comment by peti** [comment]
This is a bug in Cabal; reported in https://github.com/haskell/cabal/issues/2661.

The error occurs because we process the Cabal file with [jailbreak-cabal](http://hackage.haskell.org/package/jailbreak-cabal) to get rid of the over-specified version constraints: http://packdeps.haskellers.com/feed?needle=serversession-backend-persistent. Unfortunately, the quotations marks in your Cabal file don't survive the Cabal round-trip. :disappointed:

**Comment by meteficha** [comment]
Thanks for debugging this :).  I'll go ahead and close this issue then.
