### ISSUE TITLE
Support for newer version of Yesod

### ISSUE THREAD

**Issue by mcbahson** [yesodweb/serversession#21]
I believe serversession may need to support a newer version of Yesod.

The stack build error:
https://gist.github.com/mcbahson/a3632ee66258c49ff93426ffa26bee19

The relevant files as well as me attempting to build with cabal v2-build:
https://gist.github.com/mcbahson/b722bb98ade2306769b2b3e310d679b3

**Comment by Truedrog** [comment]
Hello! I would like to know if there are any plans to support this package?
@snoyberg, @MichaelXavier could you please bring some info about this?

Right now I've added it to my project via extra-deps by pointing it to a commit. Not sure if this is the best solution, personally I think not.

**Comment by snoyberg** [comment]
Pinging @meteficha as well.

I suppose I can do an upload, but I'd much rather clarify who the real maintainer for this package is. Felipe: are you still using/maintaining? Should we be looking for a new maintainer?

**Comment by meteficha** [comment]
I haven’t used it in a long time. It would be nice if we could find a maintainer that does (:.

**Comment by snoyberg** [comment]
Is anyone on this issue interested in stepping in as a new maintainer?

**Comment by Truedrog** [comment]
Wish I had more experience, but I am only the second month in Haskell and
never maintained anything before.

**Comment by ncaq** [comment]
I fixed maybe.
[updated: LTS: 19 by ncaq · Pull Request #27 · yesodweb/serversession](https://github.com/yesodweb/serversession/pull/27)
