### ISSUE TITLE
Persistent appears to have become incompatible with a recent release.

### ISSUE THREAD

**Issue by seanparsons** [yesodweb/serversession#24]
It appears that as `EntityDef` has gained the `entityComments` parameter that now breaks `serversession-backend-persistent` as it doesn't supply the extra parameter.

**Comment by ncaq** [comment]
I fixed.
[updated: LTS: 19 by ncaq · Pull Request #27 · yesodweb/serversession](https://github.com/yesodweb/serversession/pull/27)
