### ISSUE TITLE
Support building against safecopy 0.9

### ISSUE THREAD

**Issue by DanBurton** [yesodweb/serversession#5]
serversession-backend-acid-state has a restrictive constraint on safecopy:

https://github.com/yesodweb/serversession/blob/c528a671d448c9ab094d782c2470a5362c556dab/serversession-backend-acid-state/serversession-backend-acid-state.cabal#L23

See also: https://github.com/fpco/stackage/issues/992

**Comment by meteficha** [comment]
Thanks for reporting and sending a PR :).
